#%RAML 1.0 NamedExample

  value:
   -
     customer_id: 5
     name: 'Marija'
     surname: 'Maric'
     jmbg: '0705200000789'
     adress: 'Janka Cmelika 20'
     city: 'Prokuplje'
   -
     customer_id: 7
     name: 'Petar'
     surname: 'Peric'
     jmbg: '0705200005555'
     adress: 'Janka Veselinovica'
     city: 'Novi Pazar'