#%RAML 1.0 NamedExample
value:
  -
    employee_id: 6
    name: 'Stanko'
    surname: 'Stankovic'
    gender: 'M'
    organization_unit_id: 2
    payment_id: 2
  -
    employee_id: 7
    name: 'Mirjana'
    surname: 'Joncic'
    gender: 'F'
    organization_unit_id: 3
    payment_id: 3