#%RAML 1.0 NamedExample
value:
  -
    organization_unit_id: 2
    name: 'Ogr jedinica druga'
    adress: 'Dositeja Obradovica'
    city: 'Nis'
    contact: '+3814569658745'
  -
    organization_unit_id: 3
    name: 'Org jedinica treca'
    adress: 'Prvi maj 40'
    city: 'Pirot'
    contact: '+888951225486'