#%RAML 1.0 NamedExample
value:
  -
    payment_id: 2
    payment_method: 'Card'
    payment_date: 2022-03-20
    amount: 350
  -
    payment_id: 3
    payment_method: 'Cash'
    payment_date: 2021-07-01
    amount: 850