#%RAML 1.0 NamedExample
value:
  product_id: 3
  product_name: 'Rose'
  product_price: 990
  product_mfg_date: 2020-06-05
  product_exp_date: 2025-06-05
  product_composition: '35 Alc'
  net_weight: '200'
  gross_weight: '250'
  ditributor_id: 1
  product_type_id: 1
  employee_id: 5
  customer_id: 1