#%RAML 1.0 NamedExample
value:
  -
    product_id: 4
    product_name: 'Zdrepceva Krv'
    product_price: 1130
    product_mfg_date: 2019-03-02
    product_exp_date: 2035-10-05
    product_composition: '20 Alc'
    net_weight: '180'
    gross_weight: '200'
    ditributor_id: 2
    product_type_id: 2
    employee_id: 6
    customer_id: 2
  -
    product_id: 5
    product_name: 'Jaegermeister'
    product_price: 2000
    product_mfg_date: 2015-07-22
    product_exp_date: 2045-06-23
    product_composition: '38 Alc'
    net_weight: '500'
    gross_weight: '550'
    ditributor_id: 3
    product_type_id: 3
    employee_id: 7
    customer_id: 3