#%RAML 1.0 NamedExample
value:
  -
    user_id: 2
    name: 'Marko'
    username: 'mareee1'
    password: 'pass98'
    is_admin: false
  -
    user_id: 3
    name: 'Sanja'
    username: 'sanjab'
    password: 'sifra'
    is_admin: false