#%RAML 1.0 DataType
type: object
properties:
  product_id: integer
  product_name: string
  product_price: integer
  product_mfg_date: date-only
  product_exp_date: date-only
  product_composition: string
  net_weight: string
  gross_weight: string
  ditributor_id: integer
  product_type_id: integer
  employee_id: integer
  customer_id: integer